version: '3.8'

services:

  base:
    container_name: mabase
    image: mariadb:latest
    user: "501:20"
    command: --default-authentication-plugin=mysql_native_password
    restart: always 
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: symfony_docker
      MYSQL_USER: symfony 
      MYSQL_PASSWORD: symfony
    ports:
      - '3311:3306'
    volumes:
      - ./mysql:/var/lib/mysql

  php:
    container_name: php
    build:
      context: ./php 
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/symfo
    depends_on:
      - base 
  
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8081:80'
    volumes:
      - ./app:/var/www/symfo
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - base 
volumes:
  mysql: