controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
# nos premières routes 
#app_home:
    #path: /home
    #controller: App\Controller\HomeController::bienvenue
